import React, { useState, useEffect } from 'react';
import { supabase } from '../utils/supabase';
import { 
  Plus, Trash2, Database, AlertCircle, Loader2, Calendar, 
  CheckCircle2, Circle, WifiOff, Copy, Terminal, ChevronDown, ChevronUp, Check
} from 'lucide-react';

interface Todo {
  id: string | number;
  name: string;
  completed?: boolean;
  created_at?: string;
}

interface SupabaseErrorDetails {
  message: string;
  details?: string;
  hint?: string;
  code?: string;
}

const STARTER_TODOS: Todo[] = [
  { id: 'starter-1', name: "Set up the 'todos' table in the Supabase SQL Editor", completed: false },
  { id: 'starter-2', name: "Connect database credentials in the .env configuration", completed: true },
  { id: 'starter-3', name: "Configure Row Level Security (RLS) for anonymous access", completed: false },
];

export default function App() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [newTodoName, setNewTodoName] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [diagnostics, setDiagnostics] = useState<SupabaseErrorDetails | null>(null);
  const [isSyncing, setIsSyncing] = useState(false);
  const [isLocalMode, setIsLocalMode] = useState(false);
  const [showDiagnostics, setShowDiagnostics] = useState(false);
  const [copied, setCopied] = useState(false);

  // SQL code to create the todos table in Supabase
  const sqlSnippet = `-- 1. Create the 'todos' table
CREATE TABLE todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE todos ENABLE ROW LEVEL SECURITY;

-- 3. Create a public RLS policy for reading and updating tasks
CREATE POLICY "Allow public access" ON todos
  FOR ALL USING (true) WITH CHECK (true);`;

  // Fetch todos from Supabase
  async function fetchTodos() {
    setIsLoading(true);
    setError(null);
    setDiagnostics(null);
    try {
      const { data, error: supabaseError } = await supabase
        .from('todos')
        .select('*')
        .order('id', { ascending: true });

      if (supabaseError) {
        throw supabaseError;
      }

      if (data) {
        setTodos(data);
        setIsLocalMode(false);
      }
    } catch (err: any) {
      console.error('Supabase fetch error:', err);
      
      // Determine the kind of error
      let errorMessage = 'Failed to retrieve tasks from Supabase. Working with local state.';
      const errObj: SupabaseErrorDetails = {
        message: err.message || 'Unknown network or schema error',
        details: err.details || '',
        hint: err.hint || '',
        code: err.code || '',
      };

      if (err.code === '42P01') {
        errorMessage = "The 'todos' table does not exist in your Supabase database schema.";
      } else if (!(import.meta as any).env.VITE_SUPABASE_URL || (import.meta as any).env.VITE_SUPABASE_URL.includes('YOUR_')) {
        errorMessage = "Invalid Supabase URL or credentials configured in .env.";
      }

      setError(errorMessage);
      setDiagnostics(errObj);
      setIsLocalMode(true);

      // Attempt to load from localStorage as fallback
      const local = localStorage.getItem('web-code-studio-todos');
      if (local) {
        try {
          const parsed = JSON.parse(local);
          if (parsed && parsed.length > 0) {
            setTodos(parsed);
            return;
          }
        } catch (_) {}
      }
      
      // Seed with starter todos if localStorage is also empty
      setTodos(STARTER_TODOS);
    } finally {
      setIsLoading(false);
    }
  }

  useEffect(() => {
    fetchTodos();
  }, []);

  // Save to localStorage as fallback
  useEffect(() => {
    if (todos.length > 0) {
      localStorage.setItem('web-code-studio-todos', JSON.stringify(todos));
    }
  }, [todos]);

  // Copy SQL to clipboard
  const copyToClipboard = () => {
    navigator.clipboard.writeText(sqlSnippet);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Add a new todo
  const handleAddTodo = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTodoName.trim()) return;

    const tempId = 'local-' + Date.now();
    const newTodo: Todo = {
      id: tempId,
      name: newTodoName.trim(),
      completed: false,
    };

    // Optimistic update
    setTodos((prev) => [...prev, newTodo]);
    setNewTodoName('');

    if (isLocalMode) {
      // Local-only mode
      return;
    }

    setIsSyncing(true);
    try {
      const { data, error: supabaseError } = await supabase
        .from('todos')
        .insert([{ name: newTodo.name, completed: false }])
        .select();

      if (supabaseError) throw supabaseError;

      if (data && data[0]) {
        // Replace optimistic todo with database todo
        setTodos((prev) => prev.map((t) => (t.id === tempId ? data[0] : t)));
      }
    } catch (err: any) {
      console.warn('Could not sync addition with database, fallback to local persistence:', err);
    } finally {
      setIsSyncing(false);
    }
  };

  // Toggle todo status
  const handleToggleTodo = async (id: string | number, currentCompleted: boolean) => {
    const nextCompleted = !currentCompleted;

    // Optimistic update
    setTodos((prev) =>
      prev.map((t) => (t.id === id ? { ...t, completed: nextCompleted } : t))
    );

    if (isLocalMode || String(id).startsWith('local-')) {
      return;
    }

    setIsSyncing(true);
    try {
      const { error: supabaseError } = await supabase
        .from('todos')
        .update({ completed: nextCompleted })
        .eq('id', id);

      if (supabaseError) throw supabaseError;
    } catch (err) {
      console.warn('Could not sync status with database:', err);
    } finally {
      setIsSyncing(false);
    }
  };

  // Delete a todo
  const handleDeleteTodo = async (id: string | number) => {
    const backup = [...todos];
    // Optimistic update
    setTodos((prev) => prev.filter((t) => t.id !== id));

    if (isLocalMode || String(id).startsWith('local-')) {
      return;
    }

    setIsSyncing(true);
    try {
      const { error: supabaseError } = await supabase
        .from('todos')
        .delete()
        .eq('id', id);

      if (supabaseError) throw supabaseError;
    } catch (err) {
      console.warn('Could not sync deletion with database, rolling back:', err);
      setTodos(backup);
    } finally {
      setIsSyncing(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#fdfdfc] text-stone-800 flex flex-col font-sans selection:bg-stone-200 selection:text-stone-900">
      {/* Top Subtle Sync Status Header */}
      <header className="border-b border-stone-200/60 bg-white/70 backdrop-blur-md sticky top-0 z-10 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-stone-100 rounded-xl">
              <Database className="w-5 h-5 text-stone-700" />
            </div>
            <div>
              <h1 className="font-semibold text-stone-900 tracking-tight">Studio Agenda</h1>
              <p className="text-[10px] text-stone-500 font-semibold tracking-wider uppercase">
                Supabase Sync Engine
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {isLocalMode ? (
              <span className="flex items-center gap-1.5 text-[11px] text-amber-800 font-semibold bg-amber-50 border border-amber-200/50 px-2.5 py-1 rounded-full">
                <WifiOff className="w-3.5 h-3.5 text-amber-600" />
                Sandbox Mode
              </span>
            ) : isSyncing ? (
              <span className="flex items-center gap-1.5 text-[11px] text-indigo-700 font-semibold bg-indigo-50 border border-indigo-100 px-2.5 py-1 rounded-full animate-pulse">
                <Loader2 className="w-3 h-3 animate-spin text-indigo-600" />
                Synchronizing...
              </span>
            ) : (
              <span className="flex items-center gap-1.5 text-[11px] text-emerald-800 font-semibold bg-emerald-50 border border-emerald-100 px-2.5 py-1 rounded-full">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                Cloud Connected
              </span>
            )}
            <button
              onClick={fetchTodos}
              className="text-xs text-stone-600 hover:text-stone-900 font-semibold bg-white hover:bg-stone-50 border border-stone-200 px-3 py-1.5 rounded-lg transition-all active:scale-[0.98]"
            >
              Refresh
            </button>
          </div>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 max-w-3xl w-full mx-auto px-6 py-12">
        {/* Title Block */}
        <div className="mb-10 text-center sm:text-left">
          <h2 className="text-3xl font-light text-stone-900 tracking-tight sm:text-4xl mb-2">
            Your Project Deliverables
          </h2>
          <p className="text-stone-500 max-w-lg text-sm leading-relaxed">
            Collaborative checklist synchronized directly with your secure cloud schema in real time.
          </p>
        </div>

        {/* Supabase Error Alert / Connection status banner */}
        {error && (
          <div className="mb-8 p-5 bg-amber-50/60 border border-amber-200/60 rounded-2xl">
            <div className="flex items-start gap-3.5">
              <AlertCircle className="w-5.5 h-5.5 text-amber-600 shrink-0 mt-0.5" />
              <div className="flex-1">
                <h4 className="text-sm font-semibold text-amber-900">Database Connection Notice</h4>
                <p className="text-xs text-amber-700 mt-1 leading-relaxed">{error}</p>
                <p className="text-[11px] text-stone-500 mt-2">
                  The application has safely fallback to <strong>Sandbox Mode (Local Storage)</strong>. You can view, add, and check off items, but they won't save online until you create the table.
                </p>
                
                <button
                  type="button"
                  onClick={() => setShowDiagnostics(!showDiagnostics)}
                  className="mt-4 flex items-center gap-1 text-xs font-semibold text-amber-800 hover:text-amber-900 transition-colors"
                >
                  {showDiagnostics ? 'Hide Schema Setup Instructions' : 'Show Schema Setup Instructions'}
                  {showDiagnostics ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
                </button>
              </div>
            </div>

            {/* diagnostics panel */}
            {showDiagnostics && (
              <div className="mt-4 pt-4 border-t border-amber-200/50 space-y-4">
                {diagnostics && diagnostics.code && (
                  <div className="bg-stone-900/5 p-3 rounded-xl font-mono text-[10px] text-stone-600 flex items-center gap-2">
                    <Terminal className="w-3.5 h-3.5 text-stone-500" />
                    <span>Diagnostics: Code {diagnostics.code} | {diagnostics.message}</span>
                  </div>
                )}
                
                <div>
                  <h5 className="text-xs font-semibold text-amber-900 mb-1.5 flex items-center gap-1">
                    <span>How to initialize the table:</span>
                  </h5>
                  <ol className="text-xs text-amber-800 space-y-1 list-decimal list-inside leading-relaxed">
                    <li>Open your <a href="https://supabase.com" target="_blank" rel="noreferrer" className="underline font-semibold hover:text-amber-950">Supabase Console</a></li>
                    <li>Navigate to the <strong>SQL Editor</strong> tab on the left sidebar</li>
                    <li>Click <strong>New Query</strong>, paste the SQL schema below, and run it:</li>
                  </ol>
                </div>

                {/* SQL copy snippet */}
                <div className="relative rounded-xl overflow-hidden bg-stone-900 text-stone-300 font-mono text-xs shadow-inner">
                  <div className="flex items-center justify-between px-4 py-2 bg-stone-800 text-stone-400 border-b border-stone-800">
                    <span className="text-[10px] font-semibold tracking-wider uppercase">Schema Definition</span>
                    <button
                      onClick={copyToClipboard}
                      className="flex items-center gap-1 px-2 py-1 rounded bg-stone-700/50 hover:bg-stone-700 text-stone-300 hover:text-white transition-all text-[11px]"
                    >
                      {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                      {copied ? 'Copied!' : 'Copy SQL'}
                    </button>
                  </div>
                  <pre className="p-4 overflow-x-auto text-[11px] leading-relaxed select-all max-h-48 whitespace-pre text-emerald-400">
                    {sqlSnippet}
                  </pre>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Task Composer Form */}
        <form onSubmit={handleAddTodo} className="mb-8 flex gap-3">
          <div className="relative flex-1">
            <input
              type="text"
              value={newTodoName}
              onChange={(e) => setNewTodoName(e.target.value)}
              placeholder="Draft a new task or milestone..."
              className="w-full bg-white border border-stone-200 rounded-xl px-4 py-3 text-sm text-stone-800 placeholder-stone-400 focus:outline-none focus:border-stone-400 focus:ring-1 focus:ring-stone-400/20 transition-all shadow-sm"
            />
          </div>
          <button
            type="submit"
            className="bg-stone-900 hover:bg-stone-800 text-white font-semibold text-sm px-5 py-3 rounded-xl flex items-center gap-2 transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-stone-900 shadow-sm whitespace-nowrap"
          >
            <Plus className="w-4 h-4" />
            Add Task
          </button>
        </form>

        {/* Todos list */}
        <div className="bg-white border border-stone-200/80 rounded-2xl overflow-hidden shadow-sm">
          {isLoading ? (
            <div className="py-20 flex flex-col items-center justify-center gap-3">
              <Loader2 className="w-8 h-8 animate-spin text-stone-400" />
              <p className="text-sm text-stone-500 font-medium">Fetching secure items...</p>
            </div>
          ) : todos.length === 0 ? (
            <div className="py-20 px-6 text-center">
              <div className="w-12 h-12 rounded-full bg-stone-50 flex items-center justify-center mx-auto mb-4 border border-stone-100">
                <Calendar className="w-6 h-6 text-stone-400" />
              </div>
              <h3 className="font-semibold text-stone-800 text-base">Agenda is pristine</h3>
              <p className="text-xs text-stone-400 mt-1 max-w-sm mx-auto">
                No items found. Add a task above to kickstart synchronization.
              </p>
            </div>
          ) : (
            <div className="divide-y divide-stone-100">
              {todos.map((todo) => {
                const isCompleted = !!todo.completed;
                return (
                  <div
                    key={todo.id}
                    className="flex items-center justify-between px-5 py-4 hover:bg-stone-50/50 transition-colors group"
                  >
                    <div className="flex items-center gap-3.5 flex-1 min-w-0">
                      <button
                        type="button"
                        onClick={() => handleToggleTodo(todo.id, isCompleted)}
                        className="text-stone-400 hover:text-stone-600 transition-colors shrink-0"
                      >
                        {isCompleted ? (
                          <CheckCircle2 className="w-5 h-5 text-emerald-600 fill-emerald-50" />
                        ) : (
                          <Circle className="w-5 h-5 text-stone-300 hover:text-stone-400" />
                        )}
                      </button>
                      <span
                        className={`text-sm tracking-tight truncate ${
                          isCompleted
                            ? 'text-stone-400 line-through decoration-stone-300 font-normal'
                            : 'text-stone-700 font-medium'
                        }`}
                      >
                        {todo.name}
                      </span>
                    </div>

                    <button
                      type="button"
                      onClick={() => handleDeleteTodo(todo.id)}
                      className="text-stone-300 hover:text-red-600 p-1.5 rounded-lg hover:bg-red-50/50 transition-all opacity-0 group-hover:opacity-100 focus:opacity-100 shrink-0"
                      title="Delete task"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                );
              })}
            </div>
          )}

          {/* Table Footer Stats */}
          {!isLoading && todos.length > 0 && (
            <div className="bg-stone-50/80 px-5 py-3 border-t border-stone-100 flex items-center justify-between text-xs text-stone-500 font-medium">
              <span>
                {todos.filter((t) => t.completed).length} of {todos.length} items resolved
              </span>
              <span>
                {isLocalMode ? 'LocalStorage Engine Active' : 'Supabase Engine Active'}
              </span>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
